In [ ]:
# Import necessary libraries
import numpy as np                  # NumPy for numerical operations
import matplotlib.pyplot as plt     # Matplotlib for data visualization
import seaborn as sns               # Seaborn for enhanced data visualization
import pandas as pd                 # Pandas for data manipulation and analysis
import sklearn                      # Scikit-learn for machine learning
import warnings                     # Warnings library to filter out warnings

# Ignore warnings to keep the output clean
warnings.filterwarnings('ignore')

# Read the dataset from a CSV file
from pandas import read_csv
path = "/content/census.csv"    # Define the path to the CSV file
data = read_csv(path)           # Load the dataset from the CSV file

# Display the first few rows of the dataset
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [ ]:
df=pd.DataFrame(data)
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
print(f'Number of Rows: {df.shape[0]}')
print(f'Number of Columns: {df.shape[1]}')

for i, col in enumerate(df.columns):
  print(df.columns[i], '::\n', df[str(col)].unique(), '\n\n')

Number of Rows: 48842
Number of Columns: 15
age ::
 [25 38 28 44 18 34 29 63 24 55 65 36 26 58 48 43 20 37 40 72 45 22 23 54
 32 46 56 17 39 52 21 42 33 30 47 41 19 69 50 31 59 49 51 27 57 61 64 79
 73 53 77 80 62 35 68 66 75 60 67 71 70 90 81 74 78 82 83 85 76 84 89 88
 87 86]


workclass ::
 ['Private' 'Local-gov' '?' 'Self-emp-not-inc' 'Federal-gov' 'State-gov'
 'Self-emp-inc' 'Without-pay' 'Never-worked']


fnlwgt ::
 [226802  89814 336951 ... 129912 255835 257302]


education ::
 ['11th' 'HS-grad' 'Assoc-acdm' 'Some-college' '10th' 'Prof-school'
 '7th-8th' 'Bachelors' 'Masters' 'Doctorate' '5th-6th' 'Assoc-voc' '9th'
 '12th' '1st-4th' 'Preschool']


education-num ::
 [ 7  9 12 10  6 15  4 13 14 16  3 11  5  8  2  1]


marital-status ::
 ['Never-married' 'Married-civ-spouse' 'Widowed' 'Divorced' 'Separated'
 'Married-spouse-absent' 'Married-AF-spouse']


occupation ::
 ['Machine-op-inspct' 'Farming-fishing' 'Protective-serv' '?'
 'Other-service' 'Prof-specialty' 'Craft-repair' 'Adm-clerical'
 'Exec-managerial' 'Tech-support' 'Sales' 'Priv-house-serv'
 'Transport-moving' 'Handlers-cleaners' 'Armed-Forces']


relationship ::
 ['Own-child' 'Husband' 'Not-in-family' 'Unmarried' 'Wife' 'Other-relative']


race ::
 ['Black' 'White' 'Asian-Pac-Islander' 'Other' 'Amer-Indian-Eskimo']


sex ::
 ['Male' 'Female']


capital-gain ::
 [    0  7688  3103  6418  7298  3908 14084  5178 15024 99999  2597  2907
  4650  6497  1055  5013 27828  4934  4064  3674  2174 10605  3418   114
  2580  3411  4508  4386  8614 13550  6849  2463  3137  2885  2964  1471
 10566  2354  1424  1455  3325  4416 25236   594  2105  4787  2829   401
  4865  1264  1506 10520  3464  2653 20051  4101  1797  2407  3471  1086
  1848 14344  1151  2993  2290 15020  9386  2202  3818  2176  5455 11678
  7978  7262  6514 41310  3456  7430  2414  2062 34095  1831  6723  5060
 15831  2977  2346  3273  2329  9562  2635  4931  1731  6097   914  7896
  5556  1409  3781  3942  2538  3887 25124  7443  5721  1173  4687  6612
  6767  2961   991  2036  2936  2050  1111  2228 22040  3432  6360  2009
  1639 18481  2387]


capital-loss ::
 [   0 1721 1876 2415 1887  625 1977 2057 1429 1590 1485 2051 2377 1672
 1628 1902 1602 1741 2444 1408 2001 2042 1740 1825 1848 1719 3004 2179
 1573 2205 1258 2339 1726 2258 1340 1504 2559 1668 1974 1980 1564 2547
 2002 1669 1617  323 3175 2472 2174 1579 2129 1510 1735 2282 1870 1411
 1911 1651 1092 1762 2457 2231 2238  653 1138 2246 2603 2392 1944 1380
 2465 1421 3770 1594  213 2149 2824 1844 2467 2163 1816 1648 2206 2352
  419 1539  880  810  974 4356 2489 1755 3683 2267 2080  155 3900 2201
 2754]


hours-per-week ::
 [40 50 30 32 10 39 35 48 25 20 45 47  6 43 90 54 60 38 36 18 24 44 56 28
 16 41 22 55 14 33 37  8 12 70 15 75 52 84 42 80 68 99 65  5 17 72 53 29
 96 21 46  3  1 23 49 67 76  7  2 58 26 34  4 51 78 63 31 92 77 27 85 13
 19 98 62 66 57 11 86 59  9 64 73 61 88 79 89 74 69 87 97 94 82 91 81 95]


native-country ::
 ['United-States' '?' 'Peru' 'Guatemala' 'Mexico' 'Dominican-Republic'
 'Ireland' 'Germany' 'Philippines' 'Thailand' 'Haiti' 'El-Salvador'
 'Puerto-Rico' 'Vietnam' 'South' 'Columbia' 'Japan' 'India' 'Cambodia'
 'Poland' 'Laos' 'England' 'Cuba' 'Taiwan' 'Italy' 'Canada' 'Portugal'
 'China' 'Nicaragua' 'Honduras' 'Iran' 'Scotland' 'Jamaica' 'Ecuador'
 'Yugoslavia' 'Hungary' 'Hong' 'Greece' 'Trinadad&Tobago'
 'Outlying-US(Guam-USVI-etc)' 'France' 'Holand-Netherlands']


income ::
 ['<=50K' '>50K']

In [ ]:
description = df.describe()
print(description)

                age        fnlwgt  education-num  capital-gain  capital-loss  \
count  48842.000000  4.884200e+04   48842.000000  48842.000000  48842.000000
mean      38.643585  1.896641e+05      10.078089   1079.067626     87.502314
std       13.710510  1.056040e+05       2.570973   7452.019058    403.004552
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000
25%       28.000000  1.175505e+05       9.000000      0.000000      0.000000
50%       37.000000  1.781445e+05      10.000000      0.000000      0.000000
75%       48.000000  2.376420e+05      12.000000      0.000000      0.000000
max       90.000000  1.490400e+06      16.000000  99999.000000   4356.000000

       hours-per-week
count    48842.000000
mean        40.422382
std         12.391444
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000

In [ ]:
df.isin(['?']).sum(axis=0)

age                  0
workclass         2799
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        2809
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     857
income               0
dtype: int64

In [ ]:
df.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [ ]:
df.replace("?", np.nan, inplace = True)

In [ ]:
df.isna().sum()

age                  0
workclass         2799
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        2809
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     857
income               0
dtype: int64

In [ ]:
df=df.dropna()
df.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [ ]:
df['income_num']=df['income'].map({'<=50K':0, '>50K':1})
below_50k=(df.income_num == 0).sum()
print(below_50k)

above_50k=(df.income_num == 1).sum()
print(above_50k)

34014
11208

In [ ]:
df=df.drop(['income','fnlwgt'], axis = 1)

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["workclass"]=le.fit_transform(df["workclass"])
df["education"]=le.fit_transform(df["education"])
df["education-num"]=le.fit_transform(df["education-num"])
df["marital-status"]=le.fit_transform(df["marital-status"])
df["occupation"]=le.fit_transform(df["occupation"])
df["race"]=le.fit_transform(df["race"])
df["sex"]=le.fit_transform(df["sex"])
df["native-country"]=le.fit_transform(df["native-country"])
df["relationship"]=le.fit_transform(df["relationship"])
df.head()

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income_num
0,25,2,1,6,4,6,3,2,1,0,0,40,38,0
1,38,2,11,8,2,4,0,4,1,0,0,50,38,0
2,28,1,7,11,2,10,0,4,1,0,0,40,38,1
3,44,2,15,9,2,6,0,2,1,7688,0,40,38,1
5,34,2,0,5,4,7,1,4,1,0,0,30,38,0

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer
kbins = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')
df = kbins.fit_transform(df)
df=pd.DataFrame(df)
standard_description = df.describe()
print(standard_description)

                 0             1             2             3             4   \
count  45222.000000  45222.000000  45222.000000  45222.000000  45222.000000
mean       2.460263      3.312193      6.455354      5.841073      3.899120
std        1.816376      1.565311      2.386159      1.715153      2.280014
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        1.000000      3.000000      6.000000      5.000000      3.000000
50%        2.000000      3.000000      7.000000      6.000000      3.000000
75%        4.000000      3.000000      8.000000      8.000000      6.000000
max        9.000000      9.000000      9.000000      9.000000      9.000000

                 5             6             7             8             9   \
count  45222.000000  45222.000000  45222.000000  45222.000000  45222.000000
mean       4.105214      2.779156      8.322144      6.075428      0.067534
std        2.931010      3.095987      1.805195      4.215260      0.658918
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        1.000000      0.000000      9.000000      0.000000      0.000000
50%        4.000000      2.000000      9.000000      9.000000      0.000000
75%        6.000000      6.000000      9.000000      9.000000      0.000000
max        9.000000      9.000000      9.000000      9.000000      9.000000

                 10            11            12            13
count  45222.000000  45222.000000  45222.000000  45222.000000
mean       0.179360      3.390253      8.613529      2.230596
std        0.826228      1.401671      1.484361      3.885890
min        0.000000      0.000000      0.000000      0.000000
25%        0.000000      3.000000      9.000000      0.000000
50%        0.000000      3.000000      9.000000      0.000000
75%        0.000000      4.000000      9.000000      0.000000
max        9.000000      9.000000      9.000000      9.000000

In [ ]:
df.head()

    0    1    2    3    4    5    6    7    8    9    10   11   12   13
0  1.0  3.0  0.0  4.0  6.0  4.0  6.0  5.0  9.0  0.0  0.0  3.0  9.0  0.0
1  2.0  3.0  7.0  5.0  3.0  3.0  0.0  9.0  9.0  0.0  0.0  5.0  9.0  0.0
2  1.0  1.0  4.0  7.0  3.0  7.0  0.0  9.0  9.0  0.0  0.0  3.0  9.0  9.0
3  3.0  3.0  9.0  6.0  3.0  4.0  0.0  5.0  9.0  0.0  0.0  3.0  9.0  9.0
4  2.0  3.0  0.0  3.0  6.0  5.0  2.0  9.0  9.0  0.0  0.0  2.0  9.0  0.0

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scalar=MinMaxScaler(feature_range=(0,1))
df=scalar.fit_transform(df)
X=df[:,0:13]
Y=df[:,13]
df=pd.DataFrame(df)
scalar_description = df.describe()
print(scalar_description)

                 0             1             2             3             4   \
count  45222.000000  45222.000000  45222.000000  45222.000000  45222.000000
mean       0.273363      0.368021      0.717262      0.649008      0.433236
std        0.201820      0.173923      0.265129      0.190573      0.253335
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.111111      0.333333      0.666667      0.555556      0.333333
50%        0.222222      0.333333      0.777778      0.666667      0.333333
75%        0.444444      0.333333      0.888889      0.888889      0.666667
max        1.000000      1.000000      1.000000      1.000000      1.000000

                 5             6             7             8             9   \
count  45222.000000  45222.000000  45222.000000  45222.000000  45222.000000
mean       0.456135      0.308795      0.924683      0.675048      0.007504
std        0.325668      0.343999      0.200577      0.468362      0.073213
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.111111      0.000000      1.000000      0.000000      0.000000
50%        0.444444      0.222222      1.000000      1.000000      0.000000
75%        0.666667      0.666667      1.000000      1.000000      0.000000
max        1.000000      1.000000      1.000000      1.000000      1.000000

                 10            11            12            13
count  45222.000000  45222.000000  45222.000000  45222.000000
mean       0.019929      0.376695      0.957059      0.247844
std        0.091803      0.155741      0.164929      0.431766
min        0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.333333      1.000000      0.000000
50%        0.000000      0.333333      1.000000      0.000000
75%        0.000000      0.444444      1.000000      0.000000
max        1.000000      1.000000      1.000000      1.000000

In [ ]:
x = df.drop([10], axis=1)
y = df[10]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

KeyError: ignored

In [ ]:
# Import the necessary libraries
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold

# Create an instance of the Logistic Regression model
logistic = LogisticRegression()

# Fit (train) the Logistic Regression model on the training data
logistic.fit(X_train, y_train)

# Make predictions on the test data using the trained model
pred_y = logistic.predict(X_test)

# Create a 10-fold cross-validation object with shuffling
kfold = KFold(n_splits=10, random_state=1, shuffle=True)

# Calculate the accuracy of the model on the test data and convert it to a percentage
logistic_accuracy = (logistic.score(X_test, y_test) * 100)

# Print the accuracy of the Logistic Regression model
print(f'The Accuracy of the Model is {logistic_accuracy}')

The Accuracy of the Model is 81.18297401879492

In [ ]:
from sklearn.neural_network import MLPClassifier
neural = MLPClassifier(random_state=1, max_iter=1000).fit(X_train, y_train)
y_pred = neural.predict(X_test)
from sklearn.model_selection import KFold
kfold = KFold(n_splits=10, random_state=1, shuffle = True)
from sklearn.metrics import classification_report, confusion_matrix  ,accuracy_score
Neural_Accuracy=neural.score(X_test, y_test)*100
print(f'The Accuracy of the Model is {Neural_Accuracy}')

The Accuracy of the Model is 83.84742951907131